In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df= pd.read_csv(r"C:\Users\chitv\Desktop\kaggle\archive (1)\WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.shape

(7043, 21)

In [5]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [6]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [7]:
df["TotalCharges"]=pd.to_numeric(df["TotalCharges"], errors="coerce")

In [8]:
df["Churn"]=df.Churn.replace("No",0)
df["Churn"]=df.Churn.replace("Yes",1)

In [9]:
df.tenure.astype("float64", errors="ignore")

0        1.0
1       34.0
2        2.0
3       45.0
4        2.0
        ...
7038    24.0
7039    72.0
7040    11.0
7041     4.0
7042    66.0
Name: tenure, Length: 7043, dtype: float64

In [10]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

In [11]:
df=df.dropna()

In [12]:
df.drop("customerID",axis=1,inplace=True)

In [13]:
cols=['gender', 'SeniorCitizen', 'Partner', 'Dependents',
     'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod']

In [14]:
df1=pd.get_dummies(df,columns=cols ,drop_first=True)
df.drop(cols, axis=1,inplace=True)
df=pd.concat([df1,df],axis=1)
df=df.loc[:,~df.columns.duplicated()]

In [15]:
df.head()

,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,1,29.85,29.85,0,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,0
1,34,56.95,1889.50,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,2,53.85,108.15,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,45,42.30,1840.75,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,2,70.70,151.65,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [16]:
df.columns

Index(['tenure', 'MonthlyCharges', 'TotalCharges', 'Churn', 'gender_Male',
       'SeniorCitizen_1', 'Partner_Yes', 'Dependents_Yes', 'PhoneService_Yes',
       'MultipleLines_No phone service', 'MultipleLines_Yes',
       'InternetService_Fiber optic', 'InternetService_No',
       'OnlineSecurity_No internet service', 'OnlineSecurity_Yes',
       'OnlineBackup_No internet service', 'OnlineBackup_Yes',
       'DeviceProtection_No internet service', 'DeviceProtection_Yes',
       'TechSupport_No internet service', 'TechSupport_Yes',
       'StreamingTV_No internet service', 'StreamingTV_Yes',
       'StreamingMovies_No internet service', 'StreamingMovies_Yes',
       'Contract_One year', 'Contract_Two year', 'PaperlessBilling_Yes',
       'PaymentMethod_Credit card (automatic)',
       'PaymentMethod_Electronic check', 'PaymentMethod_Mailed check'],
      dtype='object')

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7032 entries, 0 to 7042
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   tenure                                 7032 non-null   int64
 1   MonthlyCharges                         7032 non-null   float64
 2   TotalCharges                           7032 non-null   float64
 3   Churn                                  7032 non-null   int64
 4   gender_Male                            7032 non-null   uint8
 5   SeniorCitizen_1                        7032 non-null   uint8
 6   Partner_Yes                            7032 non-null   uint8
 7   Dependents_Yes                         7032 non-null   uint8
 8   PhoneService_Yes                       7032 non-null   uint8
 9   MultipleLines_No phone service         7032 non-null   uint8
 10  MultipleLines_Yes                      7032 non-null   uint8
 11  InternetService_Fiber optic            7032 non-null   uint8
 12  InternetService_No                     7032 non-null   uint8
 13  OnlineSecurity_No internet service     7032 non-null   uint8
 14  OnlineSecurity_Yes                     7032 non-null   uint8
 15  OnlineBackup_No internet service       7032 non-null   uint8
 16  OnlineBackup_Yes                       7032 non-null   uint8
 17  DeviceProtection_No internet service   7032 non-null   uint8
 18  DeviceProtection_Yes                   7032 non-null   uint8
 19  TechSupport_No internet service        7032 non-null   uint8
 20  TechSupport_Yes                        7032 non-null   uint8
 21  StreamingTV_No internet service        7032 non-null   uint8
 22  StreamingTV_Yes                        7032 non-null   uint8
 23  StreamingMovies_No internet service    7032 non-null   uint8
 24  StreamingMovies_Yes                    7032 non-null   uint8
 25  Contract_One year                      7032 non-null   uint8
 26  Contract_Two year                      7032 non-null   uint8
 27  PaperlessBilling_Yes                   7032 non-null   uint8
 28  PaymentMethod_Credit card (automatic)  7032 non-null   uint8
 29  PaymentMethod_Electronic check         7032 non-null   uint8
 30  PaymentMethod_Mailed check             7032 non-null   uint8
dtypes: float64(2), int64(2), uint8(27)
memory usage: 460.1 KB

In [18]:
cols2=["MonthlyCharges","TotalCharges","tenure"]
from sklearn.preprocessing import MinMaxScaler
scaler= MinMaxScaler()
df[cols2]=scaler.fit_transform(df[cols2])

In [19]:
df.head()

,tenure,MonthlyCharges,TotalCharges,Churn,gender_Male,SeniorCitizen_1,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0.000000,0.115423,0.001275,0,0,0,1,0,0,1,...,0,0,0,0,0,0,1,0,1,0
1,0.464789,0.385075,0.215867,0,1,0,0,0,1,0,...,0,0,0,0,1,0,0,0,0,1
2,0.014085,0.354229,0.010310,1,1,0,0,0,1,0,...,0,0,0,0,0,0,1,0,0,1
3,0.619718,0.239303,0.210241,0,1,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
4,0.014085,0.521891,0.015330,1,0,0,0,0,1,0,...,0,0,0,0,0,0,1,0,1,0

In [20]:
X= df.drop('Churn',axis=1)
y=df.Churn

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=1)

In [22]:
len(X_train.columns)

30

In [23]:
import tensorflow as tf
from tensorflow import keras

In [24]:
model= keras.Sequential([
    keras.layers.Dense(units=15, kernel_initializer="he_uniform",activation='relu', input_dim=30),
    keras.layers.Dense(units=6, kernel_initializer="he_uniform",activation='relu'),
    keras.layers.Dense(units=1, kernel_initializer="he_uniform",activation='sigmoid')
        

])

In [25]:
model.compile(optimizer="adam", loss="binary_crossentropy",metrics=["accuracy"])

In [26]:
model.fit(X_train, y_train,epochs=100)

Epoch 1/100
165/165 [==============================] - 1s 2ms/step - loss: 0.4761 - accuracy: 0.7482
Epoch 2/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4429 - accuracy: 0.7829
Epoch 3/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4318 - accuracy: 0.7867
Epoch 4/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4271 - accuracy: 0.7920
Epoch 5/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4235 - accuracy: 0.7994
Epoch 6/100
165/165 [==============================] - 0s 891us/step - loss: 0.4218 - accuracy: 0.8003
Epoch 7/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4192 - accuracy: 0.8055
Epoch 8/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4190 - accuracy: 0.8036
Epoch 9/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4167 - accuracy: 0.8074
Epoch 10/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4153 - accuracy: 0.8094
Epoch 11/100
165/165 [==============================] - 0s 910us/step - loss: 0.4144 - accuracy: 0.8100
Epoch 12/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4140 - accuracy: 0.8070
Epoch 13/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4124 - accuracy: 0.8093
Epoch 14/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4118 - accuracy: 0.8100
Epoch 15/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4113 - accuracy: 0.8117
Epoch 16/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4105 - accuracy: 0.8081
Epoch 17/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8136
Epoch 18/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4096 - accuracy: 0.8127
Epoch 19/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4083 - accuracy: 0.8121
Epoch 20/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4076 - accuracy: 0.8121
Epoch 21/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4074 - accuracy: 0.8110
Epoch 22/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4066 - accuracy: 0.8134
Epoch 23/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4064 - accuracy: 0.8125
Epoch 24/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4054 - accuracy: 0.8121
Epoch 25/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4065 - accuracy: 0.8148
Epoch 26/100
165/165 [==============================] - 0s 1ms/step - loss: 0.4052 - accuracy: 0.8140
Epoch 27/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4044 - accuracy: 0.8149
Epoch 28/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4041 - accuracy: 0.8146
Epoch 29/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4035 - accuracy: 0.8132
Epoch 30/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4027 - accuracy: 0.8138
Epoch 31/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4019 - accuracy: 0.8149
Epoch 32/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4019 - accuracy: 0.8125
Epoch 33/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4018 - accuracy: 0.8140
Epoch 34/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4020 - accuracy: 0.8144
Epoch 35/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4008 - accuracy: 0.8159
Epoch 36/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4008 - accuracy: 0.8146
Epoch 37/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8165
Epoch 38/100
165/165 [==============================] - 0s 2ms/step - loss: 0.4001 - accuracy: 0.8142
Epoch 39/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3993 - accuracy: 0.8184
Epoch 40/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3993 - accuracy: 0.8155
Epoch 41/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3988 - accuracy: 0.8174
Epoch 42/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3981 - accuracy: 0.8180
Epoch 43/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3981 - accuracy: 0.8172
Epoch 44/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3976 - accuracy: 0.8172
Epoch 45/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3972 - accuracy: 0.8189
Epoch 46/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3964 - accuracy: 0.8168
Epoch 47/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3962 - accuracy: 0.8161
Epoch 48/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3964 - accuracy: 0.8172
Epoch 49/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3954 - accuracy: 0.8172
Epoch 50/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3948 - accuracy: 0.8168
Epoch 51/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3943 - accuracy: 0.8187
Epoch 52/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3950 - accuracy: 0.8189
Epoch 53/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3942 - accuracy: 0.8199
Epoch 54/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3941 - accuracy: 0.8184
Epoch 55/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3939 - accuracy: 0.8191
Epoch 56/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3936 - accuracy: 0.8189
Epoch 57/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3928 - accuracy: 0.8199
Epoch 58/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3929 - accuracy: 0.8191
Epoch 59/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3924 - accuracy: 0.8212
Epoch 60/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3920 - accuracy: 0.8208
Epoch 61/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3915 - accuracy: 0.8237
Epoch 62/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3916 - accuracy: 0.8197
Epoch 63/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3917 - accuracy: 0.8210: 0s - loss: 0.3925 - accuracy:
Epoch 64/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3915 - accuracy: 0.8197
Epoch 65/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3909 - accuracy: 0.8191
Epoch 66/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3901 - accuracy: 0.8208
Epoch 67/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3906 - accuracy: 0.8220
Epoch 68/100
165/165 [==============================] - 0s 940us/step - loss: 0.3903 - accuracy: 0.8206
Epoch 69/100
165/165 [==============================] - 0s 894us/step - loss: 0.3901 - accuracy: 0.8225
Epoch 70/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3896 - accuracy: 0.8195
Epoch 71/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3901 - accuracy: 0.8235
Epoch 72/100
165/165 [==============================] - 0s 816us/step - loss: 0.3894 - accuracy: 0.8206
Epoch 73/100
165/165 [==============================] - 0s 904us/step - loss: 0.3893 - accuracy: 0.8233
Epoch 74/100
165/165 [==============================] - 0s 989us/step - loss: 0.3881 - accuracy: 0.8218
Epoch 75/100
165/165 [==============================] - 0s 888us/step - loss: 0.3888 - accuracy: 0.8206
Epoch 76/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3882 - accuracy: 0.8210
Epoch 77/100
165/165 [==============================] - 0s 1ms/step - loss: 0.3872 - accuracy: 0.8229
Epoch 78/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3875 - accuracy: 0.8214
Epoch 79/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3874 - accuracy: 0.8223
Epoch 80/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3869 - accuracy: 0.8216
Epoch 81/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3866 - accuracy: 0.8218
Epoch 82/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3872 - accuracy: 0.8204
Epoch 83/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3854 - accuracy: 0.8210
Epoch 84/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3863 - accuracy: 0.8220
Epoch 85/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3861 - accuracy: 0.8208
Epoch 86/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8201
Epoch 87/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3858 - accuracy: 0.8231
Epoch 88/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3847 - accuracy: 0.8231
Epoch 89/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3845 - accuracy: 0.8223
Epoch 90/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3841 - accuracy: 0.8267
Epoch 91/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3847 - accuracy: 0.8223
Epoch 92/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3835 - accuracy: 0.8252
Epoch 93/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3836 - accuracy: 0.8242
Epoch 94/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3838 - accuracy: 0.8254
Epoch 95/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3828 - accuracy: 0.8206
Epoch 96/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3839 - accuracy: 0.8229
Epoch 97/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3827 - accuracy: 0.8246
Epoch 98/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3824 - accuracy: 0.8216
Epoch 99/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3822 - accuracy: 0.8231
Epoch 100/100
165/165 [==============================] - 0s 2ms/step - loss: 0.3820 - accuracy: 0.8244

In [27]:
model.evaluate(X_test,y_test)

55/55 [==============================] - 0s 1ms/step - loss: 0.4403 - accuracy: 0.7827

[0.4403028190135956, 0.7827076315879822]

In [28]:
y_p= model.predict(X_test)

In [29]:
y_p

array([[0.00126871],
       [0.69751394],
       [0.04101184],
       ...,
       [0.18350789],
       [0.00155139],
       [0.05144581]], dtype=float32)

In [30]:
y_pred=[]
for i in y_p:
    if i>0.5:
        y_pred.append(1)
    else:
        y_pred.append(0)

In [32]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

In [33]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1294
           1       0.61      0.48      0.54       464

    accuracy                           0.78      1758
   macro avg       0.72      0.69      0.70      1758
weighted avg       0.77      0.78      0.77      1758

[[1154  140]
 [ 242  222]]
0.782707622298066